package amyc
package codegenC

import analyzer._
import ast.SymbolicTreeModule.{And => AmyAnd, Call => AmyCall, Div => AmyDiv, Or => AmyOr, _}
import ast.Identifier
import c.{Instructions, _}
import Instructions._
import UtilsC._
import utils.{Context, Pipeline}

import scala.language.implicitConversions

// Generates C code for an Amy program
object CodeGenC extends Pipeline[(Program, SymbolTable), Module] {
  def run(ctx: Context)(v: (Program, SymbolTable)): Module = {
    val (program, table) = v

    // Generate code for an Amy module
    def cgModule(moduleDef: ModuleDef): List[Function] = {
      val ModuleDef(name, defs, optExpr) = moduleDef
      // Generate code for all functions
      defs.collect { case fd: FunDef if !builtInFunctions(fullName(name, fd.name)) =>
        cgFunction(fd, name, false)
      } ++
      // Generate code for the "main" function, which contains the module expression
      optExpr.toList.map { expr =>
        val mainFd = FunDef(Identifier.fresh("main"), Nil, TypeTree(IntType), expr)
        cgFunction(mainFd, name, true)
      }
    }

    // Generate code for a function in module 'owner'
    def cgFunction(fd: FunDef, owner: Identifier, isMain: Boolean): Function = {
      // Note: We create the c function name from a combination of
      // module and function name, since we put everything in the same c file.
      val name = fullName(owner, fd.name)
      Function(name, fd.params){
        val body = cgExpr(fd.body)
        if (isMain) {
          body <:> Drop // Main functions do not return a value,
                        // so we need to drop the value generated by their body
        } else {
          body
        }
      }
    }

    // Generate code for an expression expr.
    // Additional arguments are a mapping from identifiers (parameters and variables) to
    // their index in the wasm local variables, and a LocalsHandler which will generate
    // fresh local slots as required.
    def cgExpr(expr: Expr): Code = expr match {
      case Variable(name) => GetLocal(name)
      case IntLiteral(value) => Const(value)
      case BooleanLiteral(value) =>
        if (value) {
          Const(1)
        } else {
          Const(0)
        }
      case StringLiteral(value) => Strng(value)
      case UnitLiteral() => Const(0)
      case Plus(lhs: Expr, rhs: Expr) =>
        Add(cgExpr(lhs), cgExpr(rhs))
      case Minus(lhs: Expr, rhs: Expr) =>
        Sub(cgExpr(lhs), cgExpr(rhs))
      case Times(lhs: Expr, rhs: Expr) =>
        Mul(cgExpr(lhs), cgExpr(rhs))
      case AmyDiv(lhs: Expr, rhs: Expr) =>
        Div(cgExpr(lhs), cgExpr(rhs))
      case Mod(lhs: Expr, rhs: Expr) =>
        Rem(cgExpr(lhs), cgExpr(rhs))
      case LessThan(lhs: Expr, rhs: Expr)  =>
        Lt_s(cgExpr(lhs), cgExpr(rhs))
      case LessEquals(lhs: Expr, rhs: Expr) =>
        Le_s(cgExpr(lhs), cgExpr(rhs))
      case AmyAnd(lhs: Expr, rhs: Expr) =>
        And(cgExpr(lhs), cgExpr(rhs))
      case AmyOr(lhs: Expr, rhs: Expr) =>
        Or(cgExpr(lhs), cgExpr(rhs))
      case Equals(lhs: Expr, rhs: Expr) =>
        Eq(cgExpr(lhs), cgExpr(rhs))
      case Concat(lhs: Expr, rhs: Expr) => ???
        //Add(cgExpr(lhs), cgExpr(rhs))
      case Not(e) => cgExpr(e) <:> Eqz
      case Neg(e) => Const(0) <:> cgExpr(e)
      case AmyCall(qname, args: List[Expr]) =>
        ???
      case Sequence(e1: Expr, e2: Expr) =>
        cgExpr(e1) <:> Drop <:> cgExpr(e2)
      case Let(df, value: Expr, body: Expr) => ???
        //SetLocal(name, tpe, value) <:> cgExpr(body)
      case Ite(cond: Expr, thenn: Expr, elze: Expr) =>
        cgExpr(cond) <:> If_i32 <:> cgExpr(thenn) <:> Else <:> cgExpr(elze) <:> End
      case Match(scrut: Expr, cases: List[MatchCase]) => {
        val scrutId = 0

        def matchAndBind(p: Pattern): (Code, Map[Identifier, Int]) = p match {
          case WildcardPattern() => (Drop <:> Const(1), Map())
          case IdPattern(name) => ???
            ///(SetLocal(newLoco) <:> Const(1) ,Map(name -> newLoco))
          case LiteralPattern(lit) => ???
            //cgExpr(lit) <:> Eq, Map())
          case CaseClassPattern(con, args) => ???
        }

        val scrutCode = cgExpr(scrut)
        val matchCode = cases.map(c => {
          val (code, newLocos) = matchAndBind(c.pat)
          code <:> If_i32 <:> cgExpr(c.expr) <:> Else
        })

        scrutCode <:> matchCode <:> Strng("Match error!") <:> Unreachable <:> cases.map(_ => End)
      }
      case Error(msg: Expr) =>
        ???
    }

    Module(
      program.modules.last.name.name,
      defaultIncludes,
      globalsNo,
      cFunctions/* ++ (program.modules flatMap cgModule)*/
    )

  }
}
